[tool.poetry]
name = "home2"
version = "0.1.0"
description = ""
authors = ["Roman Sharoyan <sharoyan24@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytils = "^0.4.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
